version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"